version: 0.2
phases:
  build:
    commands:
      - npm install
      - npm run webpack
artifacts:
  files:
    - index-portfolio.html
    - style.css
    - css/*
    - images/*
    - js/*
    - dist/bundle.js
